import { createServer } from "node:http";
import { createReadStream, existsSync, statSync } from "node:fs";
import { extname, resolve, sep } from "node:path";
import { parse } from "node:url";

const PORT = Number(process.env.PORT || 50505);
const HOST = process.env.HOST || "127.0.0.1";
const STATIC_DIR = resolve(process.env.STATIC_DIR || "static");
const MIME_TYPES = {
    ".css": "text/css; charset=utf-8",
    ".html": "text/html; charset=utf-8",
    ".js": "text/javascript; charset=utf-8",
    ".json": "application/json; charset=utf-8",
    ".png": "image/png",
    ".svg": "image/svg+xml",
    ".ico": "image/x-icon",
    ".txt": "text/plain; charset=utf-8",
    ".map": "application/json; charset=utf-8"
};

const baseConfig = {
    defaultReasoningEffort: "minimal",
    defaultRetrievalReasoningEffort: "minimal",
    showMultimodalOptions: false,
    showSemanticRankerOption: false,
    showQueryRewritingOption: false,
    showReasoningEffortOption: false,
    streamingEnabled: true,
    showVectorOption: false,
    showUserUpload: false,
    showLanguagePicker: false,
    showSpeechInput: false,
    showSpeechOutputBrowser: false,
    showSpeechOutputAzure: false,
    showChatHistoryBrowser: false,
    showChatHistoryCosmos: false,
    showAgenticRetrievalOption: false,
    ragSearchTextEmbeddings: true,
    ragSearchImageEmbeddings: false,
    ragSendTextSources: true,
    ragSendImageSources: false,
    webSourceEnabled: false,
    sharepointSourceEnabled: false
};

const authSetup = {
    useLogin: false,
    requireAccessControl: false,
    enableUnauthenticatedAccess: true,
    msalConfig: {
        auth: {
            clientId: "",
            authority: "",
            redirectUri: "/redirect",
            postLogoutRedirectUri: "/",
            navigateToLoginRequestUrl: false
        },
        cache: {
            cacheLocation: "localStorage",
            storeAuthStateInCookie: false
        }
    },
    loginRequest: { scopes: [] },
    tokenRequest: { scopes: [] }
};

function writeJson(res, statusCode, body) {
    res.writeHead(statusCode, { "Content-Type": "application/json" });
    res.end(JSON.stringify(body));
}

function safeFilePath(pathname) {
    const candidate = resolve(STATIC_DIR, `.${pathname}`);
    if (candidate === STATIC_DIR || candidate.startsWith(`${STATIC_DIR}${sep}`)) {
        return candidate;
    }
    return null;
}

function serveStaticFile(req, res, filePath) {
    const extension = extname(filePath).toLowerCase();
    const contentType = MIME_TYPES[extension] || "application/octet-stream";
    res.writeHead(200, { "Content-Type": contentType });
    if (req.method === "HEAD") {
        res.end();
        return;
    }
    createReadStream(filePath).pipe(res);
}

function maybeServeStatic(req, pathname, res) {
    const target = pathname === "/" ? "/index.html" : pathname;
    const requestedPath = safeFilePath(target);

    if (requestedPath && existsSync(requestedPath) && statSync(requestedPath).isFile()) {
        serveStaticFile(req, res, requestedPath);
        return true;
    }

    // For SPA routes, fall back to index.html when a direct file is not found.
    const fallbackPath = safeFilePath("/index.html");
    if (fallbackPath && existsSync(fallbackPath) && statSync(fallbackPath).isFile()) {
        serveStaticFile(req, res, fallbackPath);
        return true;
    }

    return false;
}

function readJsonBody(req) {
    return new Promise((resolve, reject) => {
        const chunks = [];
        req.on("data", chunk => chunks.push(chunk));
        req.on("end", () => {
            if (chunks.length === 0) {
                resolve({});
                return;
            }
            try {
                resolve(JSON.parse(Buffer.concat(chunks).toString("utf8")));
            } catch (err) {
                reject(err);
            }
        });
        req.on("error", reject);
    });
}

function getLatestUserMessage(body) {
    const messages = Array.isArray(body?.messages) ? body.messages : [];
    for (let i = messages.length - 1; i >= 0; i -= 1) {
        if (messages[i]?.role === "user" && typeof messages[i]?.content === "string") {
            return messages[i].content;
        }
    }
    return "Hello from mock backend.";
}

function buildChatResponse(prompt) {
    const content = `Mock response: ${prompt}`;
    return {
        message: { role: "assistant", content },
        delta: { role: "assistant", content },
        context: {
            data_points: { text: [], images: [], citations: [] },
            followup_questions: null,
            thoughts: [{ title: "Mock backend", description: "Response generated by app/mockbackend." }]
        },
        session_state: `mock-session-${Date.now()}`
    };
}

function sendNdjsonEvent(res, event) {
    res.write(`${JSON.stringify(event)}\n`);
}

function handleStream(res, prompt) {
    const content = `Mock response: ${prompt}`;
    const chunks = content.match(/.{1,24}/g) || [content];

    res.writeHead(200, {
        "Content-Type": "application/x-ndjson",
        "Cache-Control": "no-cache",
        Connection: "keep-alive"
    });

    sendNdjsonEvent(res, {
        delta: { role: "assistant", content: "" },
        context: {
            data_points: { text: [], images: [], citations: [] },
            thoughts: [{ title: "Mock backend", description: "Streaming from mockbackend." }],
            followup_questions: null
        },
        session_state: `mock-session-${Date.now()}`
    });

    let i = 0;
    const timer = setInterval(() => {
        if (i >= chunks.length) {
            clearInterval(timer);
            sendNdjsonEvent(res, { context: { followup_questions: null } });
            res.end();
            return;
        }
        sendNdjsonEvent(res, { delta: { role: "assistant", content: chunks[i] } });
        i += 1;
    }, 60);
}

const server = createServer(async (req, res) => {
    const { pathname } = parse(req.url || "", true);
    if (!pathname) {
        writeJson(res, 404, { error: "Not found" });
        return;
    }

    if (req.method === "GET" && pathname === "/healthz") {
        writeJson(res, 200, { ok: true });
        return;
    }

    if (req.method === "GET" && pathname === "/auth_setup") {
        writeJson(res, 200, authSetup);
        return;
    }

    if (req.method === "GET" && pathname === "/.auth/me") {
        writeJson(res, 200, []);
        return;
    }

    if (req.method === "GET" && pathname === "/config") {
        writeJson(res, 200, baseConfig);
        return;
    }

    if (req.method === "POST" && pathname === "/chat") {
        try {
            const body = await readJsonBody(req);
            const prompt = getLatestUserMessage(body);
            writeJson(res, 200, buildChatResponse(prompt));
        } catch {
            writeJson(res, 400, { error: "Invalid JSON body" });
        }
        return;
    }

    if (req.method === "POST" && pathname === "/chat/stream") {
        try {
            const body = await readJsonBody(req);
            const prompt = getLatestUserMessage(body);
            handleStream(res, prompt);
        } catch {
            writeJson(res, 400, { error: "Invalid JSON body" });
        }
        return;
    }

    if (req.method === "GET" && pathname.startsWith("/content/")) {
        const citation = decodeURIComponent(pathname.slice("/content/".length));
        res.writeHead(200, { "Content-Type": "text/plain; charset=utf-8" });
        res.end(`Mock content for citation: ${citation}\n`);
        return;
    }

    if (req.method === "GET" && pathname === "/list_uploaded") {
        writeJson(res, 200, []);
        return;
    }

    if (req.method === "POST" && pathname === "/upload") {
        writeJson(res, 200, { message: "Mock upload accepted." });
        return;
    }

    if (req.method === "POST" && pathname === "/delete_uploaded") {
        writeJson(res, 200, { message: "Mock file deleted." });
        return;
    }

    if (req.method === "POST" && pathname === "/chat_history") {
        writeJson(res, 200, { message: "Mock history saved." });
        return;
    }

    if (req.method === "GET" && pathname === "/chat_history/sessions") {
        writeJson(res, 200, { sessions: [], continuation_token: null });
        return;
    }

    if (req.method === "GET" && pathname.startsWith("/chat_history/sessions/")) {
        const id = pathname.split("/").pop() || "mock";
        writeJson(res, 200, { id, entra_oid: "mock", answers: [] });
        return;
    }

    if (req.method === "DELETE" && pathname.startsWith("/chat_history/sessions/")) {
        res.writeHead(204);
        res.end();
        return;
    }

    if (req.method === "POST" && pathname === "/speech") {
        writeJson(res, 400, { error: "Speech is disabled in mockbackend." });
        return;
    }

    if ((req.method === "GET" || req.method === "HEAD") && maybeServeStatic(req, pathname, res)) {
        return;
    }

    writeJson(res, 404, { error: `No mock route for ${req.method} ${pathname}` });
});

server.listen(PORT, HOST, () => {
    // Keep startup log concise so it is easy to scan in a terminal with frontend logs.
    console.log(`mockbackend listening on http://${HOST}:${PORT} (static dir: ${STATIC_DIR})`);
});
